---
- name: install autorandr and arandr
  become: yes
  package: name={{ item }} state=present
  with_items:
  - autorandr
  - arandr

- name: create the config directory
  file:
    path: "{{ user_config_dir }}/autorandr"
    state: directory

- name: copy hooks
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ user_config_dir }}/autorandr"
    mode: 0700
  with_items:
  - postswitch
