---
- name: "Make ZSH default shell for user {{ ansible_env.USER }}"
  become: true
  user:
      name: "{{ ansible_env.USER }}"
      shell: /bin/zsh

- name: "Copy default ZSH config for user {{ ansible_env.USER }}"
  file:
      src: "{{ role_path }}/files/zshrc"
      dest: "{{ ansible_env.HOME }}/.zshrc"
      owner: "{{ ansible_env.USER }}"
      group: "{{ user_group }}"
      state: link
      force: yes

