---
- name: run setup
  hosts: "{{ custom_hosts|default('localhost') }}"
  gather_facts: yes

  vars_files:
    - "vars/common.yml"
    - ["vars/{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml",
       "vars/{{ ansible_distribution|lower }}.yml",
       "vars/unix.yml"]

  roles:
    - role: packages
      tags: ['packages', 'ui']
    - role: git
      tags: always
    - role: ZSH
    - role: vim
      tags: always
    - role: tmux
      tags: always
    - role: htop
      tags: always
    - role: python
    - role: i3-gaps
      tags: never
