---
- name: Setup this local machine
  hosts: "{{ custom_hosts|default('localhost') }}"
  gather_facts: True
  
  vars_files:
    - ["vars/{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml",
       "vars/{{ ansible_distribution|lower }}.yml",
       "vars/common.yml"]

  roles:
    - role: platform
    - role: ZSH
    - role: vim
    - role: tmux
    - role: python

