---
- name: Setup this local machine
  hosts: all
  gather_facts: True
  
  vars:
    headless: "{{ headless if headless exists else false }}"

  vars_files:
    - ["vars/{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml",
       "vars/{{ ansible_distribution|lower }}.yml",
       "vars/common.yml"]

  roles:
    - role: platform
    - role: ZSH
    - role: vim
    - role: tmux

