---
- name: installing core packages
  become: yes
  package: name={{ item }} state=latest
  with_items:
    - htop
    - xclip
    - git
    - gnome-keyring
    - libsecret
    - libva-intel-driver
    - vim
    - neovim
    - zsh
    - ranger
    - unrar
    - curl
    - wget
    - bmon
    - feh
    - python2-pip
    - python-pip  # Python 3
    - wmctrl
    - blueman
    - networkmanager
    - network-manager-applet
    - imagemagick
    - hsetroot
    - exiv2
    - tree
    - tmux
    - neofetch
    - rxvt-unicode
    - termite
    - urxvt-perls
    - deepin-calculator

- name: copy yay config files
  copy:
    src: '{{ role_path }}/files/archlinux/yay/config.json'
    dest: '{{ yay_config_file }}'
    owner: "{{ ansible_env.USER }}"
    group: "{{ user_group }}"
    force: yes

- name: install powerline fonts
  command: yay --answerdiff=None --noconfirm --needed -S powerline-fonts-git

- name: install emoji fonts
  command: yay --answerdiff=None --noconfirm --needed -S ttf-joypixels

- name: install Python3.7
  command: yay --answerdiff=None --noconfirm --needed -S python37

