---
- name: installing core packages
  become: yes
  package: name={{ item }} state=latest
  with_items:
    - htop
    - xclip
    - git
    - gnome-keyring
    - libsecret
    - vim
    - neovim
    - zsh
    - ranger
    - unrar
    - curl
    - wget
    - feh
    - python2-pip
    - python3
    - wmctrl
    - imagemagick
    - hsetroot
    - exiv2
    - tree
    - tmux
    - neofetch
    - yaourt
    - rxvt-unicode
    - rxvt-unicode-terminfo
    - urxvt-perls

- name: create the yaourt config directory
  file:
    path: "{{ yaourt_config_dir }}"
    state: directory

- name: copy the yaourt no-pain-in-the-ass-config
  copy:
    src: "{{ role_path }}/files/archlinux/yaourtrc"
    dest: "{{ yaourt_config_dir }}/yaourtrc"
    force: yes

- name: update the AUR
  command: yaourt -Syy

- name: install powerline fonts
  command: yaourt -S --noconfirm powerline-fonts-git
