---
- name: installing core packages
  become: yes
  package: name={{ item }} state=latest
  with_items:
    - htop
    - xclip
    - git
    - gnome-keyring
    - libsecret
    - vim
    - neovim
    - zsh
    - ranger
    - unrar
    - curl
    - wget
    - feh
    - python2-pip
    - python-pip  # Python 3
    - wmctrl
    - imagemagick
    - hsetroot
    - exiv2
    - tree
    - tmux
    - neofetch
    - rxvt-unicode
    - rxvt-unicode-terminfo
    - urxvt-perls
    - deepin-calculator

- name: install powerline fonts
  command: yay --nodiffmenu --nocleanmenu -S powerline-fonts-git
