---
- name: installing core packages
  become: yes
  package: name={{ item }} state=latest
  with_items:
    - htop
    - xclip
    - git
    - vim
    - neovim
    - zsh
    - unrar
    - curl
    - wget
    - feh
    - python2-pip
    - python3
    - wmctrl
    - imagemagick
    - exiv2
    - tree
    - tmux
    - neofetch
    - yaourt
    - rxvt-unicode
    - rxvt-unicode-terminfo
    - urxvt-perls

- name: update the AUR
  command: yaourt -Syy

- name: install powerline fonts
  command: yaourt -S --noconfirm powerline-fonts-git
