---
- name: update Homebrew
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: install required packages
  homebrew:
    name: [
      'bmon',
      'exiv2',
      'ffmpeg',
      'htop',
      'neofetch',
      'neovim',
      'python3',
      'ranger',
      'tmux',
      'tree',
      'vim',
      'watch',
      'wget',
      'zsh',
    ]
    state: present

- name: python virtualenvwrapper
  become: yes
  pip:
    name: "{{ item }}"
    executable: pip3
  loop:
    - virtualenv
    - virtualenvwrapper
