---
- name: ensure correct permissions of the zsh and Homebrew folders
  become: yes
  file:
    path: /usr/local
    owner: root
    group: admin
    recurse: yes
    mode: '775'  

- name: update Homebrew
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: install required packages
  homebrew:
    name: [
      'bmon',
      'exiv2',
      'htop',
      'neofetch',
      'neovim',
      'python2',
      'python3',
      'ranger',
      'tmux',
      'tree',
      'vim',
      'watch',
      'wget',
      'zsh',
    ]
    state: present

