---
- include_tasks: "virtualenv.yml"
  vars:
    pip_executable: "{{ _pip_executable }}"
  loop_control:
    loop_var: _pip_executable
  with_items:
    - "{{ pip2_bin }}"
    - "{{ pip3_bin }}"

- name: create the bpython config folder
  file:
    path: "{{ bpython_config_dir }}"
    state: directory
  tags: dotfiles

- name: copy the bpython config file
  copy:
    src: "{{ role_path }}/files/bpython/config"
    dest: "{{ bpython_config_dir }}/config"
    force: yes
  tags: dotfiles

