---
- name: "install virtualenv"
  become: yes
  pip:
    name: ['virtualenv', 'virtualenvwrapper']
    executable: '{{ pip3_bin }}'
  tags: packages

- name: create directory for virtual environments
  file:
    path: '{{ ansible_env.HOME }}/.venvs'
    state: directory
  tags: packages

- name: create the bpython config folder
  file:
    path: '{{ bpython_config_dir }}'
    state: directory
  tags: [packages, dotfiles]

- name: copy the bpython config file
  copy:
    src: '{{ role_path }}/files/bpython/config'
    dest: '{{ bpython_config_dir }}/config'
    force: yes
  tags: dotfiles

