---
- name: install pywal
  include_tasks: "{{ ansible_distribution|lower }}.yml"
  tags: ui

- name: create the pywal cache and template directories
  file: path={{ item }} state=directory
  with_items:
  - '{{ pywal_cache_dir }}'
  - '{{ pywal_template_dir }}'
  tags: ['ui', 'dotfiles-ui']

- name: copy the colors template
  copy:
    src: '{{ role_path }}/files/templates/colors.Xresources'
    dest: '{{ pywal_template_dir }}/colors.Xresources'
    force: yes
  tags: ['ui', 'dotfiles-ui']

- name: execute pywal once
  shell: wal -n -a 70 --theme sexy-monokai
  tags: ui

- name: link the colors file to the to-be-created cache file
  file:
    src: '{{ pywal_cache_dir }}/colors.Xresources'
    dest: '{{ xresources_color }}'
    state: link
  tags: [ui, dotfiles-ui]
