---
- name: install i3-gaps
  become: yes
  package: name={{ item }} state=latest
  with_items:
  - i3-gaps
  - i3exit
  - libnotify
  - notification-daemon
  - dunst
  - light-locker
  - playerctl

- name: install the sound switcher indicator
  command: yay --answerdiff=None --noconfirm --needed -S indicator-sound-switcher-git
