---
- name: Find the location of the zsh executable
  shell: which zsh
  register: zsh_bin
  tags: packages

- name: Make ZSH default shell
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ zsh_bin.stdout }}"
  tags: packages

- name: Copy default ZSH instance if it doesn't exist
  copy:
    src: "{{ role_path }}/files/.zshinstance"
    dest: "{{ ansible_env.HOME }}/.zshinstance"
    owner: "{{ ansible_env.USER }}"
    group: "{{ user_group }}"
    mode: 0700
    force: no
  tags: always

- name: Copy default ZSH config
  copy:
    src: "{{ role_path }}/files/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    owner: "{{ ansible_env.USER }}"
    group: "{{ user_group }}"
    mode: 0700
    force: yes
  tags: always

- name: Copy the OS dependent configuration
  copy:
    src: "{{ role_path }}/files/.zsh_{{ ansible_os_family|lower }}"
    dest: "{{ ansible_env.HOME }}/.zshosdep"
    owner: "{{ ansible_env.USER }}"
    group: "{{ user_group }}"
    mode: 0700
    force: yes
  tags: always

- name: Copy the aliases
  copy:
    src: "{{ role_path }}/files/.bash_aliases"
    dest: "{{ ansible_env.HOME }}/.bash_aliases"
    owner: "{{ ansible_env.USER }}"
    group: "{{ user_group }}"
    mode: 0700
    force: yes
  tags: always
