---
i3_config_dir: '{{ user_config_dir }}/i3'
i3_config_file: '{{ i3_config_dir }}/config'
compton_config_file: '{{ user_config_dir }}/compton.conf'
fonts_dir: '{{ ansible_env.HOME }}/.fonts'

placeholder_i3_exit_script: '\<i3-exit-script\>'
placeholder_i3_refresh_script: '\<i3-refresh-script\>'
placeholder_screenshot_script: '\<screenshot-script\>'

i3_exit_script: "i3exit"
i3_refresh_script: "i3refresh"
screenshot_script: "screenshot"
set_wallpaper_script: "set-wallpaper"

