---
- name: copy the tmux configuration
  file:
      src: "{{ role_path }}/files/tmux.conf"
      dest: "{{ ansible_env.HOME }}/.tmux.conf"
      owner: "{{ ansible_env.USER }}"
      group: "{{ ansible_env.USER }}"
      state: link
      force: yes

- name: create the tmux plugin directory
  file:
      path: "{{ tpm_dir }}"
      state: directory
      owner: "{{ ansible_env.USER }}"
      group: "{{ ansible_env.USER }}"
      mode: 0700

- name: clone tpm (tmux plugin manager)
  git:
      repo: https://github.com/tmux-plugins/tpm
      dest: "{{ tpm_dir }}"

