---
- name: copy the .gitignore_global file
  copy:
    src: "{{ role_path }}/files/.gitignore_global"
    dest: "{{ ansible_env.HOME }}/.gitignore_global"
    owner: "{{ ansible_env.USER }}"
    group: "{{ user_group }}"
    mode: 0700

- name: set this as the global gitignore file
  git_config:
    name: core.excludesfile
    scope: global
    value: "{{ ansible_env.HOME }}/.gitignore_global"
