---
- name: copy the .gitignore_global file
  copy:
    src: '{{ role_path }}/files/.gitignore_global'
    dest: '{{ user_home_dir }}/.gitignore_global'
    owner: "{{ ansible_env.USER }}"
    mode: 0700

- name: set this as the global gitignore file
  git_config:
    name: core.excludesfile
    scope: global
    value: "{{ user_home_dir }}/.gitignore_global"
