---
- name: update Homebrew
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: install required packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - tree
    - vim
    - htop
    - wget
    - tmux
    - neofetch
    - exiv2
    - zsh
    - python2
    - python3

- name: ensure correct permissions of the zsh folders
  file:
    path: "{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: admin
    mode: 0755
  with_items:
    - /usr/local/share/zsh
    - /usr/local/share/zsh/site-functions
