---
# Platform independent tasks
- name: create the user bin directory
  file:
    path: "{{ user_bin_dir }}"
    state: directory
    mode: 0700
  tags: always

- name: run the platform dependent tasks
  include_tasks: "execute_task.yml"
  vars:
    task_prefix: "{{ ansible_distribution|lower }}"
  loop_control:
    loop_var: task
  with_items:
    - "main"
    - "{{ ansible_distribution_major_version }}" 
  tags: always

## Possible values
# RedHat = 'RedHat'
# Fedora = 'RedHat'
# CentOS = 'RedHat'
# Scientific = 'RedHat'
# SLC = 'RedHat'
# Ascendos = 'RedHat'
# CloudLinux = 'RedHat'
# PSBM = 'RedHat',
# OracleLinux = 'RedHat'
# OVS = 'RedHat'
# OEL = 'RedHat'
# Amazon = 'RedHat',
# XenServer = 'RedHat'
# Ubuntu = 'Debian'
# Debian = 'Debian'
# SLES = 'Suse'
# SLED = 'Suse'
# OpenSuSE = 'Suse'
# SuSE = 'Suse'
# Gentoo = 'Gentoo'
# Archlinux = 'Archlinux'
# Mandriva = 'Mandrake'
# Mandrake = 'Mandrake'
# Solaris = 'Solaris'
# Nexenta = 'Solaris'
# OmniOS = 'Solaris'
# OpenIndiana = 'Solaris'
# SmartOS = 'Solaris'
# AIX = 'AIX'
# Alpine = 'Alpine'
# MacOSX = 'Darwin' or 'MacOSX'
# FreeBSD = 'FreeBSD'
# HPUX = 'HP-UX'
