---
- name: copy the tmux configuration
  copy:
      src: "{{ role_path }}/files/tmux.conf"
      dest: "{{ ansible_env.HOME }}/.tmux.conf"
      owner: "{{ ansible_env.USER }}"
      group: "{{ user_group }}"
      force: yes
  tags: dotfiles

- name: create the tmux plugin directory
  file:
      path: "{{ tpm_dir }}"
      state: directory
      owner: "{{ ansible_env.USER }}"
      group: "{{ user_group }}"
      mode: 0700
  tags: dotfiles

- name: clone tpm (tmux plugin manager)
  git:
      repo: https://github.com/tmux-plugins/tpm
      dest: "{{ tpm_dir }}"
  tags: dotfiles

- name: install the plugins
  shell: "{{ cmd }}"
  loop_control:
    loop_var: cmd
  with_items:
  - tmux start-server
  - tmux new-session -d -n plugins
  - "{{ tpm_dir }}/scripts/install_plugins.sh"

- name: update all plugins
  shell: "{{ cmd }}"
  loop_control:
    loop_var: cmd
  with_items:
  - tmux start-server
  - tmux new-session -d -n plugins
  - "{{ tpm_dir }}/scripts/update_plugin.sh all"
  tags: dotfiles

