---
- name: copy .vimrc
  file:
        src: "{{ role_path }}/files/vimrc"
        dest: "{{ ansible_env.HOME }}/.vimrc"
        owner: "{{ ansible_env.USER }}"
        group: "{{ user_group }}"
        state: link
        force: yes
        mode: 0700

- name: create vim vundle dir
  file:
        path: "{{ vundle_dir }}"
        state: directory
        owner: "{{ ansible_env.USER }}"
        group: "{{ user_group }}"
        mode: 0700

- name: clone vundle from github
  git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: "{{ vundle_dir }}"

- name: install all vim plugins
  # We use '+PluginInstall' to install all Vundle packages
  shell: vim +PluginInstall +qall

