---
- name: installing core packages
  become: true
  package: name={{ item }} state=latest
  with_items:
    - htop
    - xclip
    - lm-sensors
    - git
    - vim
    - zsh
    - unrar
    - curl
    - wget
    - feh
    - python-pip
    - python3-pip
    - fonts-powerline
    - cmake
    # begin GitKraken
    - gconf2
    - gconf-service
    - libgnome-keyring-common
    - libgnome-keyring-dev
    # end GitKraken
    - libxkbcommon-dev
    - ntfs-3g
    - sshfs
    - openvpn
    - network-manager-openvpn-gnome
    - build-essential
    # begin nethogs
    - libncurses5-dev
    - libpcap-dev
    # end nethogs
    # begin nvm for nodejs
    - checkinstall
    - libssl-dev
    # end nvm
    - wmctrl
    - arandr
    - software-properties-common
    - imagemagick
    - apcalc
    - exiv2
    - tree
    - gir1.2-gtop-2.0
    - gir1.2-networkmanager-1.0

- name: run distribution specific tasks defined by an upper bound
  include_tasks: "execute_task.yml"
  vars:
    task_prefix: "ubuntu/before"
  when: ansible_distribution_version is version_compare(task, '<=')
  with_items: "{{ supported_distribution_versions_ubuntu }}"
  loop_control:
    loop_var: task

- name: run distribution specific tasks defined by a lower bound
  include_tasks: "execute_task.yml"
  vars:
    task_prefix: "ubuntu/after"
  when: ansible_distribution_version is version_compare(task, '>=')
  with_items: "{{ supported_distribution_versions_ubuntu }}"
  loop_control:
    loop_var: task

- include_role:
    name: i3-gaps
  when: headless is not defined

