---
- name: installing core packages
  become: true
  package: name={{ item }} state=latest
  with_items:
    - htop
    - xclip
    - lm-sensors
    - git
    - vim
    - zsh
    - unrar
    - feh
    - python-pip
    - fonts-powerline
    - cmake
    # GitKraken-Begin
    - gconf2
    - gconf-service
    - libgnome-keyring-common
    - libgnome-keyring-dev
    # GitKraken-End
    - libxkbcommon-dev
    - ntfs-3g
    - openvpn
    - network-manager-openvpn-gnome
    - build-essential
    # nethogs
    - libncurses5-dev
    - libpcap-dev
    # end nethogs
    # nvm for nodejs
    - checkinstall
    - libssl-dev
    # end nvm
    - wmctrl
    - software-properties-common
    - imagemagick
    - tree

- name: run distribution specific tasks defined by an upper bound
  include_tasks: "execute_task.yml"
  vars:
    task_prefix: "ubuntu/before"
  when: ansible_distribution_version is version_compare(task, '<=')
  with_items: "{{ supported_distribution_versions_ubuntu }}"
  loop_control:
    loop_var: task

- name: run distribution specific tasks defined by a lower bound
  include_tasks: "execute_task.yml"
  vars:
    task_prefix: "ubuntu/after"
  when: ansible_distribution_version is version_compare(task, '>=')
  with_items: "{{ supported_distribution_versions_ubuntu }}"
  loop_control:
    loop_var: task

- include_role:
    name: i3
  when: not headless

