---
- name: installing core packages
  become: true
  package: name={{ item }} state=latest
  with_items:
    - htop
    - xclip
    - lm-sensors
    - git
    - vim
    - zsh
    - unrar
    - feh
    - python-pip
    - fonts-powerline
    - cmake
    - libxkbcommon-dev
    - openvpn
    - network-manager-openvpn-gnome
    - build-essential
    # nethogs
    - libncurses5-dev
    - libpcap-dev
    # end nethogs
    # nvm for nodejs
    - checkinstall
    - libssl-dev
    # end nvm
    - wmctrl
    - software-properties-common
    - imagemagick
    - tree
    - neofetch

- name: resolve dependencies for Ubuntu 14.xx and earlier
  include_tasks: "prior-ubuntu-14.yml"
  when: ansible_distribution_version is version_compare('14.10', '<=')

- name: resolve dependencies for Ubuntu 16.xx or higher
  include_tasks: "after-ubuntu-16.yml"
  when: ansible_distribution_version is version_compare('16.04', '>=')

- include_role:
    name: i3
  when: not headless

