---
- name: run the platform dependent tasks
  include_tasks: "{{ platform_task }}"
  ignore_errors: yes
  loop_control:
    loop_var: platform_task
  with_items:
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml" 

## Possible values
# RedHat = 'RedHat'
# Fedora = 'RedHat'
# CentOS = 'RedHat'
# Scientific = 'RedHat'
# SLC = 'RedHat'
# Ascendos = 'RedHat'
# CloudLinux = 'RedHat'
# PSBM = 'RedHat',
# OracleLinux = 'RedHat'
# OVS = 'RedHat'
# OEL = 'RedHat'
# Amazon = 'RedHat',
# XenServer = 'RedHat'
# Ubuntu = 'Debian'
# Debian = 'Debian'
# SLES = 'Suse'
# SLED = 'Suse'
# OpenSuSE = 'Suse'
# SuSE = 'Suse'
# Gentoo = 'Gentoo'
# Archlinux = 'Archlinux'
# Mandriva = 'Mandrake'
# Mandrake = 'Mandrake'
# Solaris = 'Solaris'
# Nexenta = 'Solaris'
# OmniOS = 'Solaris'
# OpenIndiana = 'Solaris'
# SmartOS = 'Solaris'
# AIX = 'AIX'
# Alpine = 'Alpine'
# MacOSX = 'Darwin'
# FreeBSD = 'FreeBSD'
# HPUX = 'HP-UX'