---
- name: installing core packages
  become: true
  package: name={{ item }} state=latest
  with_items:
    - htop
    - xclip
    - lm-sensors
    - git
    - vim
    - zsh
    - unrar
    - feh
    - python-pip
    - fonts-powerline
    - cmake
    - libxkbcommon-dev
    - openvpn
    - network-manager-openvpn-gnome
    - build-essential
    # nethogs
    - libncurses5-dev
    - libpcap-dev
    # end nethogs
    # nvm for nodejs
    - checkinstall
    - libssl-dev
    # end nvm
    - wmctrl
    - python-software-properties
    - software-properties-common
    - imagemagick
    - tree

- include_role:
    name: i3