---
- name: Setup this local machine
  hosts: localhost
  # connection: local
  # strategy: debug

  vars_files:
    - ["vars/{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml",
       "vars/{{ ansible_distribution|lower }}.yml",
       "vars/common.yml"]

  roles:
    - role: platform
    - role: ZSH
    - role: vim
    - role: tmux

