---
- name: make sure the htop config folder exists
  file:
    path: "{{ htop_config_dir }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ user_group }}"
    mode: 0700
  tags: dotfiles

- name: copy the htop config file
  copy:
    src: "{{ role_path }}/files/htoprc"
    dest: "{{ htop_config_dir }}/htoprc"
    owner: "{{ ansible_env.USER }}"
    group: "{{ user_group }}"
    force: yes
  tags: dotfiles
