---
- name: copy vimrcbase
  copy:
    src: "{{ role_path }}/files/vimrcbase"
    dest: "{{ vim_dir }}/vimrcbase"
    force: yes
  tags: dotfiles

- name: copy vimrc
  copy:
    src: "{{ role_path }}/files/vimrc"
    dest: "{{ vim_dir }}/vimrc"
    force: yes
  tags: dotfiles

- name: copy .ideavimrc
  copy:
    src: "{{ role_path }}/files/.ideavimrc"
    dest: "{{ansible_env.HOME }}/.ideavimrc"
    force: yes
  tags: dotfiles

- name: create vim vundle dir
  file:
    path: "{{ vundle_dir }}"
    state: directory

- name: clone vundle from github
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "{{ vundle_dir }}"

- name: install all vim plugins
  # We use '+PluginInstall' to install all Vundle packages
  shell: vim +PluginInstall +qall

