---
- name: create neovim autoload dir
  file:
    path: '{{ nvim_autoload_dir }}'
    state: directory

- name: create neovim config dir
  file:
    path: '{{ nvim_config_dir }}'
    state: directory

- name: create vim autoload dir
  file:
    path: '{{ vim_autoload_dir }}'
    state: directory

- name: copy vimrcbase
  copy:
    src: '{{ role_path }}/files/vimrcbase'
    dest: '{{ vim_dir }}/vimrcbase'
    force: yes

- name: copy vimrc
  copy:
    src: '{{ role_path }}/files/vimrc'
    dest: '{{ vim_dir }}/vimrc'
    force: yes

- name: copy .ideavimrc
  copy:
    src: '{{ role_path }}/files/.ideavimrc'
    dest: '{{ ansible_env.HOME }}/.ideavimrc'
    force: yes

- name: copy neovim init.vim
  copy:
    src: '{{ role_path }}/files/init.vim'
    dest: '{{ nvim_config_dir }}/init.vim'
    force: yes

- name: download the plug autoload script for vim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{ vim_autoload_dir }}/plug.vim'

- name: download the plug autoload script for neovim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{ nvim_autoload_dir }}/plug.vim'

- name: install dependencies
  pip:
    executable: pip3
    name:
      - pynvim
      - python-language-server
    extra_args: --user

- name: install all plugins in vim and neovim
  # We use '+PlugInstall' to install all Plug packages
  shell: "{{ item }} +'PlugInstall --sync' +qall"
  with_items:
    - vim
    - nvim

