---
- name: installing core packages
  become: yes
  package: name={{ item }} state=latest
  with_items:
    - htop
    - xclip
    - lm-sensors
    - blueman
    - git
    - vim
    - zsh
    - rxvt-unicode
    - ranger
    - unrar
    - curl
    - wget
    - feh
    - python-pip
    - python3-pip
    - python3.7
    # begin GitKraken
    - gconf2
    - gconf-service
    - libgnome-keyring-common
    - libgnome-keyring-dev
    # end GitKraken
    - ntfs-3g
    - sshfs
    - bmon
    # begin nvm for nodejs
    - checkinstall
    - libssl-dev
    # end nvm
    - wmctrl
    - imagemagick
    - hsetroot
    - exiv2
    - tree
    - rename

- name: run distribution specific tasks defined by an upper bound
  include_tasks: "execute_task.yml"
  vars:
    task_prefix: "ubuntu/before"
  when: ansible_distribution_version is version_compare(task, '<=')
  with_items: "{{ supported_distribution_versions_ubuntu }}"
  loop_control:
    loop_var: task
  tags: always

- name: run distribution specific tasks defined by a lower bound
  include_tasks: "execute_task.yml"
  vars:
    task_prefix: "ubuntu/after"
  when: ansible_distribution_version is version_compare(task, '>=')
  with_items: "{{ supported_distribution_versions_ubuntu }}"
  loop_control:
    loop_var: task
  tags: always
