---
- name: "light : install requirements"
  become: yes
  package: name={{ item }} state=latest
  with_items:
    - automake
    - autoconf

- name: "light : create temporary checkout directory"
  tempfile: state=directory suffix=.light
  register: light_repo_dir

- name: "light : clone the git repository"
  git:
    repo: https://github.com/haikarainen/light
    dest: "{{ light_repo_dir.path }}"

- name: "light : autogen"
  shell: ./autogen.sh
  args:
    chdir: "{{ light_repo_dir.path }}"

- name: "light : configure"
  shell: ./configure
  args:
    chdir: "{{ light_repo_dir.path }}"

- name: "light : make and install"
  become: yes
  make:
    chdir: "{{ light_repo_dir.path }}"
    target: install
    params:
      NUM_THREADS: "{{ ansible_processor_vcpus }}"

