---
- name: install requirements
  become: True
  package: name={{ item }} state=latest
  with_items:
    - automake
    - autoconf

- name: create temporary checkout directory
  tempfile: state=directory suffix=.light
  register: light_repo_dir

- name: clone the git repository
  git:
    repo: https://github.com/haikarainen/light
    dest: "{{ light_repo_dir.path }}"
    version: v1.1.2

- name: autogen
  shell: autogen.sh
  args:
    chdir:"{{ light_repo_dir.path }}"

- name: configure
  shell: configure.sh
  args:
    chdir:"{{ light_repo_dir.path }}"

- name: make and install
  become: True
  shell: "make -j{{ ansible_processor_vcpus }} install"
  args:
    chdir:"{{ light_repo_dir.path }}"
