---
- name: make sure that the i3 package is not installed (i3 without gaps)
  become: True
  package: name={{ item }} state=absent
  with_items:
    - i3*

- name: detect if i3-gaps is already installed
  shell: command -v i3 >/dev/null 2>&1
  register: cmd_exists_i3_gaps
  ignore_errors: yes

- name: detect if light is already installed
  shell: command -v light >/dev/null 2>&1
  register: cmd_exists_light
  ignore_errors: True

- name: create i3 config directory
  file:
    path: "{{ i3_dir }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ user_group }}"
    mode: 0700

- name: copy the config file
  copy:
    src: "{{ role_path }}/files/config"
    dest: "{{ i3_dir }}/config"
    owner: "{{ ansible_env.USER }}"
    group: "{{ user_group }}"
    mode: 0700
    force: yes

- name: copy .Xresources
  copy:
    src: "{{ role_path }}/files/.Xresources"
    dest: "{{ ansible_env.HOME }}/.Xresources"
    owner: "{{ ansible_env.USER }}"
    group: "{{ user_group }}"
    mode: 0700

- name: reload .Xresources
  command: xrdb .Xresources
  args:
    chdir: "{{ ansible_env.HOME }}"

- name: install i3-gaps
  include_tasks: install-i3.yml
  when: cmd_exists_i3_gaps.rc > 0

- name: install polybar
  include_role:
    name: polybar

- name: install light
  include_tasks: install-light.yml
  when: cmd_exists_light.rc > 0

- name: install i3-gaps requirements from source
  include_tasks: font-awesome.yml
